name: readme-header-data

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Create header image
        run: python3 readme_header/build.py


      - name: Commit and push header data
        run: |
          BRANCH=readme-header-data

          # Delete branch if exists
          if git ls-remote origin $BRANCH | grep $BRANCH;
          then
            git push -d origin $BRANCH
          fi

          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git switch --orphan $BRANCH
          git add images/header-image.svg
          git commit -m "Create header image" --author=\
          "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          git push -u origin $BRANCH
